import Head from 'next/head'
import { NextRouter, useRouter } from 'next/router';
import React, { FC } from 'react'
import styles from '../../styles/Home.module.scss'
import { NavBar } from '../Navbar/NavBar'
import { MainLayoutProps } from '../../props/MainLayout';


export const MainLayout: FC<MainLayoutProps> = ({ children }) => {
    const router: NextRouter = useRouter();
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main >
                    <NavBar path={router.pathname} />
                    {children}
                </main>
                <footer>
                    <h2>Soy el footer</h2>
                </footer>
            </div>
        </>
    )
}
